### ISSUE TITLE
*** No rule to make target `Release/obj.target/WebUDP/../WuHostNode.o'

### ISSUE THREAD

**Issue by notedit** [seemk/WebUDP#4]
```
*** No rule to make target `Release/obj.target/WebUDP/../WuHostNode.o', needed by `Release/WebUDP.node'
```
i am on mac,  steps to produce

```
mkdir build && cd build 
cmake -DWITH_NODE=ON  -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib ..
make  
```

**Comment by seemk** [comment]
It built on my Mac (macOS 10.12), however I got a runtime error when loading WebUDP.node on Mac. I'll investigate this. Are you on macOS 10.12 or some other version?

**Comment by seemk** [comment]
Ok, I fixed the initialization error (6ef564fc4422e6e9d91632c8b8d57d8c7c96958a), it now works on macOS for me. I'll try to reproduce your build error.

**Comment by notedit** [comment]
my macOS  is  10.12.6 (16G29)

update your commit  still have this error.

make[3]: *** No rule to make target
`Release/obj.target/WebUDP/../WuHostNode.o', needed by
`Release/WebUDP.node'.  Stop.

2017-12-31 18:29 GMT+08:00 Siim Kallas <notifications@github.com>:

**Comment by seemk** [comment]
Can you try building it manually in the ```build``` directory?
```
npm run configure
npm run build
```
I suspect that the WORKING_DIRECTORY in CMakeLists.txt is wrong for you (https://github.com/seemk/WebUDP/blob/master/CMakeLists.txt#L123), but that is only a guess.

**Comment by notedit** [comment]
same error.

i am not familiar with cmake.   sorry.

2017-12-31 18:44 GMT+08:00 Siim Kallas <notifications@github.com>:

**Comment by notedit** [comment]
ok  reclone it and build,  it woks now.  thanks
